services:
  postgres:
    image: docker.io/library/postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kampusia

    ports:
      - "5432:5432"

    volumes:
      - kampusia_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d kampusia"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  kampusia_postgres_data: