import { requireRole } from '../../middleware/authorization';
import { academicWrite } from '../../utils/academic-write';
import { MasterDataError, normalizeText, requirePatch } from '../../utils/master-data';
import { AuthError, type AuthUser } from '../auth/auth.model';
import { awardGrade, decimalHundredths, formatHundredths, weightedFinal } from './grading-policy';
import type { KomponenNilaiInput, KomponenNilaiPatch, KoreksiNilaiInput, NilaiInput } from './nilai.model';
import type { NilaiRepository, NilaiTransaction } from './nilai.repository';

const managers = ['ADMIN', 'AKADEMIK'] as const;
function componentWrite(input: Partial<KomponenNilaiInput>) {
  if (input.urutan !== undefined && (!Number.isInteger(input.urutan) || input.urutan < 1 || input.urutan > 32767)) throw new MasterDataError(400, 'Urutan komponen harus berupa bilangan bulat positif.');
  return { ...(input.nama !== undefined ? { nama: normalizeText(input.nama, 'Nama komponen', 100) } : {}), ...(input.bobot !== undefined ? { bobot: formatHundredths(decimalHundredths(input.bobot, 'Bobot', 1n, 10000n)) } : {}), ...(input.urutan !== undefined ? { urutan: input.urutan } : {}), ...(input.is_active !== undefined ? { isActive: input.is_active } : {}) };
}
const score = (value: string | null) => value === null ? null : formatHundredths(decimalHundredths(value, 'Nilai', 0n, 10000n));
const activeWeight = (components: readonly { isActive: boolean; bobot: string }[]) => formatHundredths(components.filter(row => row.isActive).reduce((sum, row) => sum + decimalHundredths(row.bobot, 'Bobot', 1n, 10000n), 0n));

export function createNilaiService(repository: NilaiRepository) {
  const run = <T>(operation: (tx: NilaiTransaction) => Promise<T>) => academicWrite(() => repository.transaction(operation));
  async function access(tx: NilaiTransaction, user: AuthUser, classId: string, finalization = false) {
    const current = await tx.actor(user.id);
    if (!current?.isActive || current.role !== user.role) throw new AuthError(403, 'Akun tidak memiliki izin mengelola penilaian.');
    if ((managers as readonly string[]).includes(user.role)) return;
    requireRole(user, ['DOSEN']);
    const lecturer = await tx.lecturer(user.id);
    if (!lecturer?.isActive) throw new AuthError(403, 'Dosen aktif yang ditugaskan diperlukan untuk mengelola penilaian.');
    const assignment = await tx.assignment(classId, lecturer.id);
    if (!assignment) throw new AuthError(403, 'Dosen hanya dapat mengelola penilaian kelas yang ditugaskan kepadanya.');
    if (finalization) { const coordinator = await tx.coordinator(classId); if (coordinator && coordinator.dosenId !== lecturer.id) throw new AuthError(403, 'Hanya koordinator kelas yang dapat melakukan finalisasi nilai.'); }
  }
  async function lockedClass(tx: NilaiTransaction, user: AuthUser, classId: string, finalization = false) {
    const kelas = await tx.lockClass(classId); if (!kelas) throw new MasterDataError(404, 'Kelas kuliah tidak ditemukan.'); await access(tx, user, classId, finalization); return kelas;
  }
  async function ensureMutable(tx: NilaiTransaction, classId: string) { if ((await tx.results(classId, true)).length) throw new MasterDataError(409, 'Penilaian telah difinalisasi; konfigurasi dan nilai biasa sudah dibekukan.'); }
  function ensureUniqueName(components: readonly { id: string; nama: string; isActive: boolean }[], name: string, active: boolean, except?: string) {
    if (active && components.some(row => row.id !== except && row.isActive && row.nama.trim().toLocaleLowerCase('id-ID') === name.trim().toLocaleLowerCase('id-ID'))) throw new MasterDataError(409, 'Nama komponen aktif sudah digunakan pada kelas ini.');
  }
  return {
    listComponents(user: AuthUser, classId: string) { return run(async tx => { const kelas = await tx.classInfo(classId); if (!kelas) throw new MasterDataError(404, 'Kelas kuliah tidak ditemukan.'); await access(tx, user, classId); const [components, results] = await Promise.all([tx.components(classId), tx.results(classId)]); return { success: true as const, kelas, data: components, summary: { activeWeight: activeWeight(components), activeCount: components.filter(row => row.isActive).length, finalized: results.length > 0 } }; }); },
    createComponent(user: AuthUser, classId: string, input: KomponenNilaiInput) { return run(async tx => { await lockedClass(tx, user, classId); await ensureMutable(tx, classId); const components = await tx.components(classId, true); const values = { ...componentWrite(input), isActive: input.is_active ?? true }; ensureUniqueName(components, values.nama!, values.isActive); return tx.createComponent(classId, values as { nama: string; bobot: string; urutan: number; isActive: boolean }); }); },
    updateComponent(user: AuthUser, classId: string, componentId: string, input: KomponenNilaiPatch) { return run(async tx => { requirePatch(input); await lockedClass(tx, user, classId); await ensureMutable(tx, classId); const components = await tx.components(classId, true); const component = components.find(row => row.id === componentId); if (!component) throw new MasterDataError(404, 'Komponen nilai tidak ditemukan pada kelas ini.'); const values = componentWrite(input); const next = { ...component, ...values }; ensureUniqueName(components, next.nama, next.isActive, component.id); return tx.updateComponent(component.id, values); }); },
    deleteComponent(user: AuthUser, classId: string, componentId: string) { return run(async tx => { await lockedClass(tx, user, classId); await ensureMutable(tx, classId); const component = await tx.component(componentId, true); if (!component || component.kelasKuliahId !== classId) throw new MasterDataError(404, 'Komponen nilai tidak ditemukan pada kelas ini.'); if (await tx.scoreCount(componentId)) throw new MasterDataError(409, 'Komponen yang sudah memiliki nilai tidak boleh dihapus; nonaktifkan untuk mempertahankan riwayat.'); return tx.deleteComponent(componentId); }); },
    roster(user: AuthUser, classId: string) { return run(async tx => { const kelas = await tx.classInfo(classId); if (!kelas) throw new MasterDataError(404, 'Kelas kuliah tidak ditemukan.'); await access(tx, user, classId); const [components, roster, scores, results] = await Promise.all([tx.components(classId), tx.effectiveRoster(classId), tx.scores(classId), tx.results(classId)]); const active = components.filter(row => row.isActive); const effectiveIds = new Set(roster.map(row => row.id)); const rows = roster.map(mahasiswa => { const studentScores = active.map(component => ({ componentId: component.id, nilai: scores.find(row => row.mahasiswaId === mahasiswa.id && row.komponenNilaiId === component.id)?.nilai ?? null })); const complete = studentScores.every(item => item.nilai !== null); const preview = complete && active.length ? weightedFinal(studentScores.map(item => ({ nilai: item.nilai!, bobot: active.find(component => component.id === item.componentId)!.bobot }))) : null; return { mahasiswa, scores: studentScores, complete, preview, hasilStudi: results.find(row => row.mahasiswaId === mahasiswa.id) ?? null }; }); return { kelas, components, data: rows, historicalScores: scores.filter(row => !effectiveIds.has(row.mahasiswaId) || !row.komponen.isActive), summary: { activeWeight: activeWeight(components), activeCount: active.length, totalStudents: roster.length, completeStudents: rows.filter(row => row.complete).length, missingScores: rows.reduce((sum, row) => sum + row.scores.filter(item => item.nilai === null).length, 0), finalized: results.length > 0 } }; }); },
    record(user: AuthUser, classId: string, studentId: string, componentId: string, input: NilaiInput) { return run(async tx => { const planIds = await tx.relatedPlanIds(classId, studentId); await tx.lockPlans(planIds); await lockedClass(tx, user, classId); await ensureMutable(tx, classId); const component = await tx.component(componentId, true); if (!component || component.kelasKuliahId !== classId) throw new MasterDataError(404, 'Komponen nilai tidak ditemukan pada kelas ini.'); if (!component.isActive) throw new MasterDataError(409, 'Nilai biasa hanya dapat dicatat pada komponen aktif.'); if (!(await tx.effectiveRoster(classId)).some(row => row.id === studentId)) throw new MasterDataError(400, 'Mahasiswa tidak terdaftar efektif pada kelas ini.'); return tx.upsertScore(componentId, studentId, score(input.nilai), user.id); }); },
    finalize(user: AuthUser, classId: string) { return run(async tx => { const planIds = await tx.relatedPlanIds(classId); await tx.lockPlans(planIds); const kelas = await lockedClass(tx, user, classId, true); if (kelas.status !== 'DITUTUP') throw new MasterDataError(409, 'Finalisasi nilai hanya dapat dilakukan saat kelas berstatus DITUTUP.'); const [components, roster, scores, existing] = await Promise.all([tx.components(classId, true), tx.effectiveRoster(classId), tx.scores(classId, true), tx.results(classId, true)]); if (existing.length) throw new MasterDataError(409, 'Nilai kelas sudah difinalisasi. Gunakan koreksi terkontrol.'); const active = components.filter(row => row.isActive); if (!active.length) throw new MasterDataError(409, 'Finalisasi memerlukan setidaknya satu komponen nilai aktif.'); const totalWeight = activeWeight(active); if (totalWeight !== '100.00') throw new MasterDataError(409, `Total bobot komponen aktif harus 100.00%; saat ini ${totalWeight}%.`); if (!roster.length) throw new MasterDataError(409, 'Finalisasi memerlukan setidaknya satu mahasiswa dengan KRS efektif.'); const finalizedAt = new Date(); const rows = roster.map(student => { const values = active.map(component => { const value = scores.find(row => row.mahasiswaId === student.id && row.komponenNilaiId === component.id)?.nilai; if (value === null || value === undefined) throw new MasterDataError(409, `Nilai belum lengkap untuk ${student.nim} — ${student.nama}.`); return { nilai: value, bobot: component.bobot }; }); const nilaiAngka = weightedFinal(values); const award = awardGrade(nilaiAngka); return { kelasKuliahId: classId, mahasiswaId: student.id, nilaiAngka, nilaiHuruf: award.nilaiHuruf, nilaiIndeks: award.nilaiIndeks, difinalisasiAt: finalizedAt, difinalisasiOleh: user.id }; }); return { data: await tx.insertResults(rows), finalizedAt }; }); },
    correct(user: AuthUser, classId: string, studentId: string, input: KoreksiNilaiInput) { return run(async tx => { requireRole(user, managers); const reason = input.alasan.trim(); if (!reason) throw new MasterDataError(400, 'Alasan koreksi wajib diisi.'); await lockedClass(tx, user, classId); const [components, scores, results] = await Promise.all([tx.components(classId, true), tx.scores(classId, true), tx.results(classId, true)]); const result = results.find(row => row.mahasiswaId === studentId); if (!result) throw new MasterDataError(404, 'Hasil studi mahasiswa tidak ditemukan pada kelas ini.'); const component = components.find(row => row.id === input.component_id); if (!component?.isActive) throw new MasterDataError(400, 'Koreksi harus menggunakan komponen aktif pada konfigurasi final.'); const existingScore = scores.find(row => row.mahasiswaId === studentId && row.komponenNilaiId === component.id); if (!existingScore) throw new MasterDataError(409, 'Nilai sumber tidak ditemukan; koreksi tidak boleh membuat hasil yang tidak lengkap.'); const newScore = score(input.nilai)!; await tx.upsertScore(component.id, studentId, newScore, user.id); const values = components.filter(row => row.isActive).map(item => { const value = item.id === component.id ? newScore : scores.find(row => row.mahasiswaId === studentId && row.komponenNilaiId === item.id)?.nilai; if (value === null || value === undefined) throw new MasterDataError(409, 'Koreksi ditolak karena nilai komponen aktif mahasiswa tidak lengkap.'); return { nilai: value, bobot: item.bobot }; }); const nilaiAngka = weightedFinal(values); const award = awardGrade(nilaiAngka); const correctedAt = new Date(); return tx.updateResult(result.id, { nilaiAngka, nilaiHuruf: award.nilaiHuruf, nilaiIndeks: award.nilaiIndeks, dikoreksiAt: correctedAt, dikoreksiOleh: user.id, alasanKoreksi: reason }); }); },
  };
}
export type NilaiService = ReturnType<typeof createNilaiService>;
